import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import './globals.css'
import Head from "next/head";
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
const comfortaa = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `Servio`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={comfortaa.className}>
      <Navbar />
        <div className='text-white  lg:mt-20 mt-16 '>      
        {children}
        </div>
        <Footer />
        </body>
    </html>
  )
}
